# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ae986ab912161433c33845237bbde9b6ba174762d2afe47b60083ddb72e8000f4c6800e3a4fcd720e2ec6b4b251f4ed605e904dbfe1fc9645a001ac3e82763

test:
  secret_key_base: 457b2d02b9b6416dced552751340e071a19b616e8690171728308050bc87d17840c20f200755aa2d613e5f6abe84424259834086a26e0dd3a80072a3b9aadef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
